Add docker file for Ubuntu 24.04
Build errors related to Ceres use of hypot and fpclassify appeared. Claude added a compatibility header. In his words:

The compilation error in Ubuntu 24.04 was due to Ceres 2.2.0 using C++ standard library functions (std::hypot with 3 arguments and std::fpclassify) that don't have overloads for Eigen::AutoDiffScalar types. Solution:

1. Created a new compatibility header opensfm/src/bundle/error/autodiff_ceres_compat.h with the missing function overloads

2. Included this header in opensfm/src/bundle/error/error_utils.h:8 before the Ceres headers