Do not use constepr to fix compile error when not using buck
Summary:
Not sure what is going on here but when building opensfm with `python3 setup.py build` instead of using buck, we get this error
```
/Users/paugargallo/pro/OpenSfM/opensfm/src/geometry/test/camera_test.cc:581:18: error: constexpr variable 'inv_normalizer' must be initialized by a constant expression
  constexpr auto inv_normalizer = 1.0 / std::max(width, height);
```
Also in travis https://travis-ci.org/github/mapillary/OpenSfM/builds/742970785
So fixing by just not using constexpr

Reviewed By: YanNoun

Differential Revision: D24915972

fbshipit-source-id: c78c38d882057e187aaf310413c6598a33eca1b5