create_rigs: fail gracefully on malformed datasets
Summary:
create_rigs will crash if the dataset doesn't have enough rig images:

```
I0506 20:13:03.296000 581 rig.py:224] Found 1 shots for instance 3221-1572994022__0000000880.jpg using pattern matching.
I0506 20:13:03.296000 581 rig.py:224] Found 1 shots for instance 3221-1572808750__0000003372.jpg using pattern matching.
I0506 20:13:03.296000 581 rig.py:227] Found 2 single shots using pattern matching.
rig.py:235] Running SfM on a subset of 0 images.

ZeroDivisionError: division by zero

  File "opensfm/rig.py", line 237, in create_rigs_with_pattern
    actions.detect_features.run_dataset(subset_data)
  File "opensfm/actions/detect_features.py", line 40, in run_dataset
    chunks_count = math.ceil(len(all_images) / chunk_size)
```

This fix just returns if there aren't enough images.

Reviewed By: YanNoun

Differential Revision: D28280855

fbshipit-source-id: 0c39c4ef901ea4768ecc506853ffe9ac420b1611